name: customers-service-actions
on: [push]
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'
      - run: npm install
      - run: npm run test

