name: customers-service-actions
on:
  push:
    branches:
      - 'main'
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          test-script: npm run test:cov
          threshold: 80
  deploy:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'customers-service-121'
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
